const constants = {
  IDLE_SCREEN_WIDTH: 375,
  RESTART_DELAY_MILISECONDS: 100,
  IDLE_SCREEN_HEIGHT: 812,
  XS_MAX_SCREEN_WIDTH: 414,
  XS_MAX_SCREEN_HEIGHT: 896,
  NETWORK_CONNECTION_ERROR: 408,
};

export default constants;
